import AgenticAxtell.Baseline.FixedGroup
import Mathlib.Analysis.MeanInequalities

namespace AgenticAxtell.Baseline

theorem weighted_two_geom_eq_arith_iff {weight₁ weight₂ value₁ value₂ : ℝ}
    (weight₁Positive : 0 < weight₁) (weight₂Positive : 0 < weight₂)
    (value₁Nonnegative : 0 ≤ value₁) (value₂Nonnegative : 0 ≤ value₂)
    (weightsSum : weight₁ + weight₂ = 1) :
    value₁ ^ weight₁ * value₂ ^ weight₂ = weight₁ * value₁ + weight₂ * value₂ ↔
      value₁ = value₂ := by
  have equalityCondition := Real.geom_mean_eq_arith_mean_weighted_iff'
    (s := Finset.univ) ![weight₁, weight₂] ![value₁, value₂]
    (by intro i _; fin_cases i <;> simp [weight₁Positive, weight₂Positive])
    (by simpa using weightsSum)
    (by intro i _; fin_cases i <;> simp [value₁Nonnegative, value₂Nonnegative])
  rw [show (∑ i : Fin 2, ![weight₁, weight₂] i * ![value₁, value₂] i) =
      weight₁ * value₁ + weight₂ * value₂ by simp [Fin.sum_univ_two]] at equalityCondition
  rw [show (∏ i : Fin 2, ![value₁, value₂] i ^ ![weight₁, weight₂] i) =
      value₁ ^ weight₁ * value₂ ^ weight₂ by simp [Fin.prod_univ_two]] at equalityCondition
  constructor
  · intro equality
    have condition := equalityCondition.mp equality
    have first := condition 0 (Finset.mem_univ 0)
    have second := condition 1 (Finset.mem_univ 1)
    simpa using first.trans second.symm
  · intro valuesEqual
    subst value₂
    apply equalityCondition.mpr
    intro i _
    fin_cases i <;> simp_all <;> nlinarith

/-- The closed-form candidate obtained from the interior first-order condition
when production is linear. It is deliberately named `Candidate` until its
global optimality for the utility function has been proved. For nonnegative
other effort and `theta ≤ 1`, the upper clamp is redundant. -/
def linearBestResponseCandidate (theta othersEffort : ℝ) : ℝ :=
  max 0 (theta - (1 - theta) * othersEffort)

/-- Weighted AM-GM in the normalization generated by the interior
linear-production first-order condition. -/
theorem normalized_linear_cobbDouglas_le_one (theta othersEffort effort : ℝ)
    (thetaPositive : 0 < theta) (thetaAtMostOne : theta < 1)
    (othersNonnegative : 0 ≤ othersEffort) (effortFeasible : effort ∈ FeasibleEffort) :
    ((effort + othersEffort) / (theta * (1 + othersEffort))) ^ theta *
        ((1 - effort) / ((1 - theta) * (1 + othersEffort))) ^ (1 - theta) ≤ 1 := by
  have thetaNonnegative : 0 ≤ theta := thetaPositive.le
  have oneMinusPositive : 0 < 1 - theta := sub_pos.mpr thetaAtMostOne
  have onePlusPositive : 0 < 1 + othersEffort := by linarith
  have firstDenominatorPositive : 0 < theta * (1 + othersEffort) :=
    mul_pos thetaPositive onePlusPositive
  have secondDenominatorPositive : 0 < (1 - theta) * (1 + othersEffort) :=
    mul_pos oneMinusPositive onePlusPositive
  have firstFactorNonnegative :
      0 ≤ (effort + othersEffort) / (theta * (1 + othersEffort)) :=
    div_nonneg (add_nonneg effortFeasible.1 othersNonnegative) firstDenominatorPositive.le
  have secondFactorNonnegative :
      0 ≤ (1 - effort) / ((1 - theta) * (1 + othersEffort)) :=
    div_nonneg (sub_nonneg.mpr effortFeasible.2) secondDenominatorPositive.le
  have weighted := Real.geom_mean_le_arith_mean2_weighted thetaNonnegative
    oneMinusPositive.le firstFactorNonnegative secondFactorNonnegative (by ring)
  calc
    _ ≤ theta * ((effort + othersEffort) / (theta * (1 + othersEffort))) +
        (1 - theta) * ((1 - effort) / ((1 - theta) * (1 + othersEffort))) := weighted
    _ = 1 := by
      field_simp
      ring

theorem normalized_linear_cobbDouglas_lt_one_of_ne_candidate
    (theta othersEffort effort : ℝ) (thetaPositive : 0 < theta)
    (thetaAtMostOne : theta < 1) (othersNonnegative : 0 ≤ othersEffort)
    (effortFeasible : effort ∈ FeasibleEffort)
    (interior : (1 - theta) * othersEffort < theta)
    (effortNeCandidate : effort ≠ linearBestResponseCandidate theta othersEffort) :
    ((effort + othersEffort) / (theta * (1 + othersEffort))) ^ theta *
        ((1 - effort) / ((1 - theta) * (1 + othersEffort))) ^ (1 - theta) < 1 := by
  let firstFactor := (effort + othersEffort) / (theta * (1 + othersEffort))
  let secondFactor := (1 - effort) / ((1 - theta) * (1 + othersEffort))
  have onePlusPositive : 0 < 1 + othersEffort := by linarith
  have firstDenominatorPositive : 0 < theta * (1 + othersEffort) :=
    mul_pos thetaPositive onePlusPositive
  have secondDenominatorPositive : 0 < (1 - theta) * (1 + othersEffort) :=
    mul_pos (sub_pos.mpr thetaAtMostOne) onePlusPositive
  have firstFactorNonnegative : 0 ≤ firstFactor :=
    div_nonneg (add_nonneg effortFeasible.1 othersNonnegative)
      firstDenominatorPositive.le
  have secondFactorNonnegative : 0 ≤ secondFactor :=
    div_nonneg (sub_nonneg.mpr effortFeasible.2) secondDenominatorPositive.le
  have factorsNe : firstFactor ≠ secondFactor := by
    intro factorsEqual
    have effortFormula : effort = theta - (1 - theta) * othersEffort := by
      dsimp [firstFactor, secondFactor] at factorsEqual
      field_simp at factorsEqual
      nlinarith
    apply effortNeCandidate
    rw [linearBestResponseCandidate,
      max_eq_right (le_of_lt (sub_pos.mpr interior))]
    exact effortFormula
  have weightedLe := Real.geom_mean_le_arith_mean2_weighted thetaPositive.le
    (sub_pos.mpr thetaAtMostOne).le firstFactorNonnegative secondFactorNonnegative
    (by ring)
  have weightedNe :
      firstFactor ^ theta * secondFactor ^ (1 - theta) ≠
        theta * firstFactor + (1 - theta) * secondFactor := by
    exact (weighted_two_geom_eq_arith_iff thetaPositive (sub_pos.mpr thetaAtMostOne)
      firstFactorNonnegative secondFactorNonnegative (by ring)).not.mpr factorsNe
  have weightedLt :
      firstFactor ^ theta * secondFactor ^ (1 - theta) <
        theta * firstFactor + (1 - theta) * secondFactor :=
    lt_of_le_of_ne weightedLe weightedNe
  have arithmeticEq : theta * firstFactor + (1 - theta) * secondFactor = 1 := by
    dsimp [firstFactor, secondFactor]
    field_simp
    ring
  simpa [firstFactor, secondFactor, arithmeticEq] using weightedLt

theorem linearBestResponseCandidate_eq_interior (theta othersEffort : ℝ)
    (interior : (1 - theta) * othersEffort < theta) :
    linearBestResponseCandidate theta othersEffort =
      theta - (1 - theta) * othersEffort := by
  exact max_eq_right (le_of_lt (sub_pos.mpr interior))

theorem interior_candidate_totalEffort (theta othersEffort : ℝ)
    (interior : (1 - theta) * othersEffort < theta) :
    linearBestResponseCandidate theta othersEffort + othersEffort =
      theta * (1 + othersEffort) := by
  rw [linearBestResponseCandidate_eq_interior theta othersEffort interior]
  ring

theorem interior_candidate_leisure (theta othersEffort : ℝ)
    (interior : (1 - theta) * othersEffort < theta) :
    1 - linearBestResponseCandidate theta othersEffort =
      (1 - theta) * (1 + othersEffort) := by
  rw [linearBestResponseCandidate_eq_interior theta othersEffort interior]
  ring

theorem linear_cobbDouglas_product_maximized_at_interior_candidate
    (theta othersEffort effort : ℝ) (thetaPositive : 0 < theta)
    (thetaAtMostOne : theta < 1) (othersNonnegative : 0 ≤ othersEffort)
    (effortFeasible : effort ∈ FeasibleEffort)
    (interior : (1 - theta) * othersEffort < theta) :
    (effort + othersEffort) ^ theta * (1 - effort) ^ (1 - theta) ≤
      (linearBestResponseCandidate theta othersEffort + othersEffort) ^ theta *
        (1 - linearBestResponseCandidate theta othersEffort) ^ (1 - theta) := by
  have thetaDenominatorPositive : 0 < theta * (1 + othersEffort) :=
    mul_pos thetaPositive (by linarith)
  have leisureDenominatorPositive : 0 < (1 - theta) * (1 + othersEffort) :=
    mul_pos (sub_pos.mpr thetaAtMostOne) (by linarith)
  have totalNonnegative : 0 ≤ effort + othersEffort :=
    add_nonneg effortFeasible.1 othersNonnegative
  have leisureNonnegative : 0 ≤ 1 - effort := sub_nonneg.mpr effortFeasible.2
  have normalized := normalized_linear_cobbDouglas_le_one theta othersEffort effort
    thetaPositive thetaAtMostOne othersNonnegative effortFeasible
  rw [Real.div_rpow totalNonnegative thetaDenominatorPositive.le,
    Real.div_rpow leisureNonnegative leisureDenominatorPositive.le] at normalized
  have ratioBound :
      ((effort + othersEffort) ^ theta * (1 - effort) ^ (1 - theta)) /
          ((theta * (1 + othersEffort)) ^ theta *
            ((1 - theta) * (1 + othersEffort)) ^ (1 - theta)) ≤ 1 := by
    simpa [div_mul_div_comm] using normalized
  have poweredDenominatorPositive :
      0 < (theta * (1 + othersEffort)) ^ theta *
        ((1 - theta) * (1 + othersEffort)) ^ (1 - theta) :=
    mul_pos (Real.rpow_pos_of_pos thetaDenominatorPositive _)
      (Real.rpow_pos_of_pos leisureDenominatorPositive _)
  have rawBound := (div_le_one poweredDenominatorPositive).mp ratioBound
  rw [interior_candidate_totalEffort theta othersEffort interior,
    interior_candidate_leisure theta othersEffort interior]
  exact rawBound

theorem linear_cobbDouglas_product_strictly_maximized_at_interior_candidate
    (theta othersEffort effort : ℝ) (thetaPositive : 0 < theta)
    (thetaAtMostOne : theta < 1) (othersNonnegative : 0 ≤ othersEffort)
    (effortFeasible : effort ∈ FeasibleEffort)
    (interior : (1 - theta) * othersEffort < theta)
    (effortNeCandidate : effort ≠ linearBestResponseCandidate theta othersEffort) :
    (effort + othersEffort) ^ theta * (1 - effort) ^ (1 - theta) <
      (linearBestResponseCandidate theta othersEffort + othersEffort) ^ theta *
        (1 - linearBestResponseCandidate theta othersEffort) ^ (1 - theta) := by
  have thetaDenominatorPositive : 0 < theta * (1 + othersEffort) :=
    mul_pos thetaPositive (by linarith)
  have leisureDenominatorPositive : 0 < (1 - theta) * (1 + othersEffort) :=
    mul_pos (sub_pos.mpr thetaAtMostOne) (by linarith)
  have totalNonnegative : 0 ≤ effort + othersEffort :=
    add_nonneg effortFeasible.1 othersNonnegative
  have leisureNonnegative : 0 ≤ 1 - effort := sub_nonneg.mpr effortFeasible.2
  have normalized := normalized_linear_cobbDouglas_lt_one_of_ne_candidate
    theta othersEffort effort thetaPositive thetaAtMostOne othersNonnegative
    effortFeasible interior effortNeCandidate
  rw [Real.div_rpow totalNonnegative thetaDenominatorPositive.le,
    Real.div_rpow leisureNonnegative leisureDenominatorPositive.le] at normalized
  have ratioBound :
      ((effort + othersEffort) ^ theta * (1 - effort) ^ (1 - theta)) /
          ((theta * (1 + othersEffort)) ^ theta *
            ((1 - theta) * (1 + othersEffort)) ^ (1 - theta)) < 1 := by
    simpa [div_mul_div_comm] using normalized
  have poweredDenominatorPositive :
      0 < (theta * (1 + othersEffort)) ^ theta *
        ((1 - theta) * (1 + othersEffort)) ^ (1 - theta) :=
    mul_pos (Real.rpow_pos_of_pos thetaDenominatorPositive _)
      (Real.rpow_pos_of_pos leisureDenominatorPositive _)
  have rawBound := (div_lt_one poweredDenominatorPositive).mp ratioBound
  rw [interior_candidate_totalEffort theta othersEffort interior,
    interior_candidate_leisure theta othersEffort interior]
  exact rawBound

theorem linear_utility_strictly_maximized_at_interior_candidate
    (params : Params) (theta othersEffort effort : ℝ) (groupSize : Nat)
    (linearProduction : params.b = 0) (aPositive : 0 < params.a)
    (groupSizePositive : 0 < groupSize) (thetaPositive : 0 < theta)
    (thetaAtMostOne : theta < 1) (othersNonnegative : 0 ≤ othersEffort)
    (effortFeasible : effort ∈ FeasibleEffort)
    (interior : (1 - theta) * othersEffort < theta)
    (effortNeCandidate : effort ≠ linearBestResponseCandidate theta othersEffort) :
    utility params theta effort othersEffort groupSize <
      utility params theta (linearBestResponseCandidate theta othersEffort)
        othersEffort groupSize := by
  have rawStrict := linear_cobbDouglas_product_strictly_maximized_at_interior_candidate
    theta othersEffort effort thetaPositive thetaAtMostOne othersNonnegative
    effortFeasible interior effortNeCandidate
  have incomeCoefficientPositive : 0 < params.a / (groupSize : ℝ) :=
    div_pos aPositive (Nat.cast_pos.mpr groupSizePositive)
  have effortTotalNonnegative : 0 ≤ effort + othersEffort :=
    add_nonneg effortFeasible.1 othersNonnegative
  have candidateTotalNonnegative :
      0 ≤ linearBestResponseCandidate theta othersEffort + othersEffort :=
    add_nonneg (le_max_left _ _) othersNonnegative
  unfold utility production
  rw [linearProduction]
  simp only [zero_mul, add_zero]
  rw [show params.a * (effort + othersEffort) / (groupSize : ℝ) =
      (params.a / (groupSize : ℝ)) * (effort + othersEffort) by ring]
  rw [show params.a *
        (linearBestResponseCandidate theta othersEffort + othersEffort) /
          (groupSize : ℝ) =
      (params.a / (groupSize : ℝ)) *
        (linearBestResponseCandidate theta othersEffort + othersEffort) by ring]
  rw [Real.mul_rpow incomeCoefficientPositive.le effortTotalNonnegative,
    Real.mul_rpow incomeCoefficientPositive.le candidateTotalNonnegative]
  simpa only [mul_assoc] using mul_lt_mul_of_pos_left rawStrict
    (Real.rpow_pos_of_pos incomeCoefficientPositive theta)

theorem linearBestResponseCandidate_unique_interior
    (params : Params) (theta othersEffort effort : ℝ) (groupSize : Nat)
    (linearProduction : params.b = 0) (aPositive : 0 < params.a)
    (groupSizePositive : 0 < groupSize) (thetaPositive : 0 < theta)
    (thetaAtMostOne : theta < 1) (othersNonnegative : 0 ≤ othersEffort)
    (interior : (1 - theta) * othersEffort < theta)
    (best : IsBestResponse params theta othersEffort groupSize effort) :
    effort = linearBestResponseCandidate theta othersEffort := by
  by_contra effortNeCandidate
  have candidateNonnegative : 0 ≤ linearBestResponseCandidate theta othersEffort :=
    le_max_left _ _
  have candidateAtMostOne : linearBestResponseCandidate theta othersEffort ≤ 1 := by
    unfold linearBestResponseCandidate
    apply max_le
    · norm_num
    · have productNonnegative : 0 ≤ (1 - theta) * othersEffort :=
        mul_nonneg (sub_nonneg.mpr thetaAtMostOne.le) othersNonnegative
      linarith
  have candidateFeasible :
      linearBestResponseCandidate theta othersEffort ∈ FeasibleEffort :=
    ⟨candidateNonnegative, candidateAtMostOne⟩
  have candidateLeEffort := best.2 _ candidateFeasible
  have effortLtCandidate := linear_utility_strictly_maximized_at_interior_candidate
    params theta othersEffort effort groupSize linearProduction aPositive
    groupSizePositive thetaPositive thetaAtMostOne othersNonnegative best.1 interior
    effortNeCandidate
  exact (not_lt_of_ge candidateLeEffort) effortLtCandidate

/-- In the interior regime, the closed-form candidate is a genuine global best
response for linear production. -/
theorem linearBestResponseCandidate_isBestResponse_interior
    (params : Params) (theta othersEffort : ℝ) (groupSize : Nat)
    (linearProduction : params.b = 0) (aNonnegative : 0 ≤ params.a)
    (thetaPositive : 0 < theta) (thetaAtMostOne : theta < 1)
    (othersNonnegative : 0 ≤ othersEffort)
    (interior : (1 - theta) * othersEffort < theta) :
    IsBestResponse params theta othersEffort groupSize
      (linearBestResponseCandidate theta othersEffort) := by
  have candidateNonnegative : 0 ≤ linearBestResponseCandidate theta othersEffort :=
    le_max_left _ _
  have candidateAtMostOne : linearBestResponseCandidate theta othersEffort ≤ 1 := by
    unfold linearBestResponseCandidate
    apply max_le
    · norm_num
    · have productNonnegative : 0 ≤ (1 - theta) * othersEffort :=
        mul_nonneg (sub_nonneg.mpr thetaAtMostOne.le) othersNonnegative
      linarith
  have candidateFeasible :
      linearBestResponseCandidate theta othersEffort ∈ FeasibleEffort :=
    ⟨candidateNonnegative, candidateAtMostOne⟩
  refine ⟨candidateFeasible, ?_⟩
  intro effort effortFeasible
  have rawBound := linear_cobbDouglas_product_maximized_at_interior_candidate
    theta othersEffort effort thetaPositive thetaAtMostOne othersNonnegative
    effortFeasible interior
  have incomeCoefficientNonnegative : 0 ≤ params.a / (groupSize : ℝ) :=
    div_nonneg aNonnegative (Nat.cast_nonneg groupSize)
  have effortTotalNonnegative : 0 ≤ effort + othersEffort :=
    add_nonneg effortFeasible.1 othersNonnegative
  have candidateTotalNonnegative :
      0 ≤ linearBestResponseCandidate theta othersEffort + othersEffort :=
    add_nonneg candidateNonnegative othersNonnegative
  unfold utility production
  rw [linearProduction]
  simp only [zero_mul, add_zero]
  rw [show params.a * (effort + othersEffort) / (groupSize : ℝ) =
      (params.a / (groupSize : ℝ)) * (effort + othersEffort) by ring]
  rw [show params.a *
        (linearBestResponseCandidate theta othersEffort + othersEffort) /
          (groupSize : ℝ) =
      (params.a / (groupSize : ℝ)) *
        (linearBestResponseCandidate theta othersEffort + othersEffort) by ring]
  rw [Real.mul_rpow incomeCoefficientNonnegative effortTotalNonnegative,
    Real.mul_rpow incomeCoefficientNonnegative candidateTotalNonnegative]
  simpa only [mul_assoc] using mul_le_mul_of_nonneg_left rawBound
    (Real.rpow_nonneg incomeCoefficientNonnegative theta)

theorem linear_cobbDouglas_product_maximized_at_zero
    (theta othersEffort effort : ℝ) (thetaPositive : 0 < theta)
    (thetaAtMostOne : theta < 1) (othersNonnegative : 0 ≤ othersEffort)
    (effortFeasible : effort ∈ FeasibleEffort)
    (boundary : theta ≤ (1 - theta) * othersEffort) :
    (effort + othersEffort) ^ theta * (1 - effort) ^ (1 - theta) ≤
      othersEffort ^ theta := by
  have othersPositive : 0 < othersEffort := by
    by_contra notPositive
    have othersZero : othersEffort = 0 := le_antisymm (le_of_not_gt notPositive)
      othersNonnegative
    rw [othersZero, mul_zero] at boundary
    linarith
  have firstFactorNonnegative : 0 ≤ (effort + othersEffort) / othersEffort :=
    div_nonneg (add_nonneg effortFeasible.1 othersNonnegative) othersPositive.le
  have leisureNonnegative : 0 ≤ 1 - effort := sub_nonneg.mpr effortFeasible.2
  have weighted := Real.geom_mean_le_arith_mean2_weighted thetaPositive.le
    (sub_pos.mpr thetaAtMostOne).le firstFactorNonnegative leisureNonnegative (by ring)
  have slopeNonpositive : theta / othersEffort - (1 - theta) ≤ 0 := by
    have divided := (div_le_iff₀ othersPositive).2 boundary
    linarith
  have arithmeticBound :
      theta * ((effort + othersEffort) / othersEffort) +
        (1 - theta) * (1 - effort) ≤ 1 := by
    rw [show theta * ((effort + othersEffort) / othersEffort) +
          (1 - theta) * (1 - effort) =
        1 + effort * (theta / othersEffort - (1 - theta)) by
      field_simp
      ring]
    exact add_le_of_nonpos_right (mul_nonpos_of_nonneg_of_nonpos effortFeasible.1
      slopeNonpositive)
  have normalized :
      ((effort + othersEffort) / othersEffort) ^ theta *
        (1 - effort) ^ (1 - theta) ≤ 1 := le_trans weighted arithmeticBound
  rw [Real.div_rpow (add_nonneg effortFeasible.1 othersNonnegative)
    othersPositive.le] at normalized
  have ratioBound :
      ((effort + othersEffort) ^ theta * (1 - effort) ^ (1 - theta)) /
        othersEffort ^ theta ≤ 1 := by
    simpa [div_mul_eq_mul_div] using normalized
  exact (div_le_one (Real.rpow_pos_of_pos othersPositive theta)).mp ratioBound

theorem linear_cobbDouglas_product_strictly_maximized_at_zero
    (theta othersEffort effort : ℝ) (thetaPositive : 0 < theta)
    (thetaAtMostOne : theta < 1) (othersNonnegative : 0 ≤ othersEffort)
    (effortFeasible : effort ∈ FeasibleEffort)
    (boundary : theta ≤ (1 - theta) * othersEffort) (effortNeZero : effort ≠ 0) :
    (effort + othersEffort) ^ theta * (1 - effort) ^ (1 - theta) <
      othersEffort ^ theta := by
  have effortPositive : 0 < effort := lt_of_le_of_ne effortFeasible.1 (Ne.symm effortNeZero)
  have othersPositive : 0 < othersEffort := by
    by_contra notPositive
    have othersZero : othersEffort = 0 := le_antisymm (le_of_not_gt notPositive)
      othersNonnegative
    rw [othersZero, mul_zero] at boundary
    linarith
  let firstFactor := (effort + othersEffort) / othersEffort
  let secondFactor := 1 - effort
  have firstFactorNonnegative : 0 ≤ firstFactor :=
    div_nonneg (add_nonneg effortFeasible.1 othersNonnegative) othersPositive.le
  have secondFactorNonnegative : 0 ≤ secondFactor := sub_nonneg.mpr effortFeasible.2
  have weightedLe := Real.geom_mean_le_arith_mean2_weighted thetaPositive.le
    (sub_pos.mpr thetaAtMostOne).le firstFactorNonnegative secondFactorNonnegative
    (by ring)
  have arithmeticFormula :
      theta * firstFactor + (1 - theta) * secondFactor =
        1 + effort * (theta / othersEffort - (1 - theta)) := by
    dsimp [firstFactor, secondFactor]
    field_simp
    ring
  have normalizedStrict : firstFactor ^ theta * secondFactor ^ (1 - theta) < 1 := by
    by_cases boundaryStrict : theta < (1 - theta) * othersEffort
    · have slopeNegative : theta / othersEffort - (1 - theta) < 0 := by
        have divided := (div_lt_iff₀ othersPositive).2 boundaryStrict
        linarith
      calc
        _ ≤ theta * firstFactor + (1 - theta) * secondFactor := weightedLe
        _ = 1 + effort * (theta / othersEffort - (1 - theta)) := arithmeticFormula
        _ < 1 := by nlinarith
    · have boundaryEq : theta = (1 - theta) * othersEffort :=
        le_antisymm boundary (le_of_not_gt boundaryStrict)
      have factorsNe : firstFactor ≠ secondFactor := by
        intro factorsEqual
        dsimp [firstFactor, secondFactor] at factorsEqual
        field_simp at factorsEqual
        nlinarith
      have weightedNe :
          firstFactor ^ theta * secondFactor ^ (1 - theta) ≠
            theta * firstFactor + (1 - theta) * secondFactor :=
        (weighted_two_geom_eq_arith_iff thetaPositive (sub_pos.mpr thetaAtMostOne)
          firstFactorNonnegative secondFactorNonnegative (by ring)).not.mpr factorsNe
      have weightedLt := lt_of_le_of_ne weightedLe weightedNe
      have slopeZero : theta / othersEffort - (1 - theta) = 0 := by
        apply sub_eq_zero.mpr
        exact (div_eq_iff (ne_of_gt othersPositive)).2 boundaryEq
      calc
        _ < theta * firstFactor + (1 - theta) * secondFactor := weightedLt
        _ = 1 + effort * (theta / othersEffort - (1 - theta)) := arithmeticFormula
        _ = 1 := by rw [slopeZero]; ring
  dsimp [firstFactor, secondFactor] at normalizedStrict
  rw [Real.div_rpow (add_nonneg effortFeasible.1 othersNonnegative)
    othersPositive.le] at normalizedStrict
  have ratioBound :
      ((effort + othersEffort) ^ theta * (1 - effort) ^ (1 - theta)) /
        othersEffort ^ theta < 1 := by
    simpa [div_mul_eq_mul_div] using normalizedStrict
  exact (div_lt_one (Real.rpow_pos_of_pos othersPositive theta)).mp ratioBound

theorem linear_utility_strictly_maximized_at_zero
    (params : Params) (theta othersEffort effort : ℝ) (groupSize : Nat)
    (linearProduction : params.b = 0) (aPositive : 0 < params.a)
    (groupSizePositive : 0 < groupSize) (thetaPositive : 0 < theta)
    (thetaAtMostOne : theta < 1) (othersNonnegative : 0 ≤ othersEffort)
    (effortFeasible : effort ∈ FeasibleEffort)
    (boundary : theta ≤ (1 - theta) * othersEffort) (effortNeZero : effort ≠ 0) :
    utility params theta effort othersEffort groupSize <
      utility params theta 0 othersEffort groupSize := by
  have rawStrict := linear_cobbDouglas_product_strictly_maximized_at_zero
    theta othersEffort effort thetaPositive thetaAtMostOne othersNonnegative
    effortFeasible boundary effortNeZero
  have incomeCoefficientPositive : 0 < params.a / (groupSize : ℝ) :=
    div_pos aPositive (Nat.cast_pos.mpr groupSizePositive)
  have effortTotalNonnegative : 0 ≤ effort + othersEffort :=
    add_nonneg effortFeasible.1 othersNonnegative
  unfold utility production
  rw [linearProduction]
  simp only [zero_mul, add_zero]
  rw [show params.a * (effort + othersEffort) / (groupSize : ℝ) =
      (params.a / (groupSize : ℝ)) * (effort + othersEffort) by ring]
  simp only [zero_add, sub_zero, Real.one_rpow, mul_one]
  rw [show params.a * othersEffort / (groupSize : ℝ) =
      (params.a / (groupSize : ℝ)) * othersEffort by ring]
  rw [Real.mul_rpow incomeCoefficientPositive.le effortTotalNonnegative,
    Real.mul_rpow incomeCoefficientPositive.le othersNonnegative]
  simpa only [mul_assoc] using mul_lt_mul_of_pos_left rawStrict
    (Real.rpow_pos_of_pos incomeCoefficientPositive theta)

theorem linearBestResponseCandidate_unique_boundary
    (params : Params) (theta othersEffort effort : ℝ) (groupSize : Nat)
    (linearProduction : params.b = 0) (aPositive : 0 < params.a)
    (groupSizePositive : 0 < groupSize) (thetaPositive : 0 < theta)
    (thetaAtMostOne : theta < 1) (othersNonnegative : 0 ≤ othersEffort)
    (boundary : theta ≤ (1 - theta) * othersEffort)
    (best : IsBestResponse params theta othersEffort groupSize effort) :
    effort = linearBestResponseCandidate theta othersEffort := by
  have candidateZero : linearBestResponseCandidate theta othersEffort = 0 :=
    max_eq_left (by linarith)
  rw [candidateZero]
  by_contra effortNeZero
  have zeroFeasible : (0 : ℝ) ∈ FeasibleEffort := by simp [FeasibleEffort]
  have zeroLeEffort := best.2 0 zeroFeasible
  have effortLtZero := linear_utility_strictly_maximized_at_zero params theta
    othersEffort effort groupSize linearProduction aPositive groupSizePositive
    thetaPositive thetaAtMostOne othersNonnegative best.1 boundary effortNeZero
  exact (not_lt_of_ge zeroLeEffort) effortLtZero

/-- In the binding-floor regime, zero—the closed-form candidate—is a global
best response for linear production. -/
theorem linearBestResponseCandidate_isBestResponse_boundary
    (params : Params) (theta othersEffort : ℝ) (groupSize : Nat)
    (linearProduction : params.b = 0) (aNonnegative : 0 ≤ params.a)
    (thetaPositive : 0 < theta) (thetaAtMostOne : theta < 1)
    (othersNonnegative : 0 ≤ othersEffort)
    (boundary : theta ≤ (1 - theta) * othersEffort) :
    IsBestResponse params theta othersEffort groupSize
      (linearBestResponseCandidate theta othersEffort) := by
  have candidateZero : linearBestResponseCandidate theta othersEffort = 0 :=
    max_eq_left (by
      linarith)
  have candidateFeasible :
      linearBestResponseCandidate theta othersEffort ∈ FeasibleEffort := by
    rw [candidateZero]
    simp [FeasibleEffort]
  refine ⟨candidateFeasible, ?_⟩
  intro effort effortFeasible
  have rawBound := linear_cobbDouglas_product_maximized_at_zero theta othersEffort
    effort thetaPositive thetaAtMostOne othersNonnegative effortFeasible boundary
  have incomeCoefficientNonnegative : 0 ≤ params.a / (groupSize : ℝ) :=
    div_nonneg aNonnegative (Nat.cast_nonneg groupSize)
  have effortTotalNonnegative : 0 ≤ effort + othersEffort :=
    add_nonneg effortFeasible.1 othersNonnegative
  unfold utility production
  rw [linearProduction]
  simp only [zero_mul, add_zero]
  rw [show params.a * (effort + othersEffort) / (groupSize : ℝ) =
      (params.a / (groupSize : ℝ)) * (effort + othersEffort) by ring]
  rw [candidateZero]
  simp only [zero_add, sub_zero, Real.one_rpow, mul_one]
  rw [show params.a * othersEffort / (groupSize : ℝ) =
      (params.a / (groupSize : ℝ)) * othersEffort by ring]
  rw [Real.mul_rpow incomeCoefficientNonnegative effortTotalNonnegative,
    Real.mul_rpow incomeCoefficientNonnegative othersNonnegative]
  simpa only [mul_assoc] using mul_le_mul_of_nonneg_left rawBound
    (Real.rpow_nonneg incomeCoefficientNonnegative theta)

/-- Complete identification of the linear-production best response for
`0 ≤ theta < 1`, including both the interior and binding-floor branches. -/
theorem linearBestResponseCandidate_isBestResponse
    (params : Params) (theta othersEffort : ℝ) (groupSize : Nat)
    (linearProduction : params.b = 0) (aNonnegative : 0 ≤ params.a)
    (thetaNonnegative : 0 ≤ theta) (thetaAtMostOne : theta < 1)
    (othersNonnegative : 0 ≤ othersEffort) :
    IsBestResponse params theta othersEffort groupSize
      (linearBestResponseCandidate theta othersEffort) := by
  by_cases thetaZero : theta = 0
  · subst theta
    have candidateZero : linearBestResponseCandidate 0 othersEffort = 0 := by
      simp [linearBestResponseCandidate, othersNonnegative]
    rw [candidateZero]
    exact theta_zero_bestResponse_zero params othersEffort groupSize
  · have thetaPositive : 0 < theta := lt_of_le_of_ne thetaNonnegative (Ne.symm thetaZero)
    by_cases boundary : theta ≤ (1 - theta) * othersEffort
    · exact linearBestResponseCandidate_isBestResponse_boundary params theta othersEffort
        groupSize linearProduction aNonnegative thetaPositive thetaAtMostOne
        othersNonnegative boundary
    · exact linearBestResponseCandidate_isBestResponse_interior params theta othersEffort
        groupSize linearProduction aNonnegative thetaPositive thetaAtMostOne
        othersNonnegative (lt_of_not_ge boundary)

theorem linearBestResponseCandidate_unique
    (params : Params) (theta othersEffort effort : ℝ) (groupSize : Nat)
    (linearProduction : params.b = 0) (aPositive : 0 < params.a)
    (groupSizePositive : 0 < groupSize) (thetaNonnegative : 0 ≤ theta)
    (thetaAtMostOne : theta < 1) (othersNonnegative : 0 ≤ othersEffort)
    (best : IsBestResponse params theta othersEffort groupSize effort) :
    effort = linearBestResponseCandidate theta othersEffort := by
  by_cases thetaZero : theta = 0
  · subst theta
    have effortZero := theta_zero_bestResponse_unique params othersEffort groupSize effort best
    have candidateZero : linearBestResponseCandidate 0 othersEffort = 0 := by
      simp [linearBestResponseCandidate, othersNonnegative]
    exact effortZero.trans candidateZero.symm
  · have thetaPositive : 0 < theta := lt_of_le_of_ne thetaNonnegative (Ne.symm thetaZero)
    by_cases boundary : theta ≤ (1 - theta) * othersEffort
    · exact linearBestResponseCandidate_unique_boundary params theta othersEffort effort
        groupSize linearProduction aPositive groupSizePositive thetaPositive
        thetaAtMostOne othersNonnegative boundary best
    · exact linearBestResponseCandidate_unique_interior params theta othersEffort effort
        groupSize linearProduction aPositive groupSizePositive thetaPositive
        thetaAtMostOne othersNonnegative (lt_of_not_ge boundary) best

theorem linearBestResponseCandidate_nonnegative (theta othersEffort : ℝ) :
    0 ≤ linearBestResponseCandidate theta othersEffort := by
  exact le_max_left _ _

theorem linearBestResponseCandidate_atMostOne (theta othersEffort : ℝ)
    (thetaAtMostOne : theta ≤ 1) (othersNonnegative : 0 ≤ othersEffort) :
    linearBestResponseCandidate theta othersEffort ≤ 1 := by
  apply max_le
  · norm_num
  · have coefficientNonnegative : 0 ≤ 1 - theta := sub_nonneg.mpr thetaAtMostOne
    have productNonnegative : 0 ≤ (1 - theta) * othersEffort :=
      mul_nonneg coefficientNonnegative othersNonnegative
    linarith

theorem linearBestResponseCandidate_feasible (theta othersEffort : ℝ)
    (thetaAtMostOne : theta ≤ 1) (othersNonnegative : 0 ≤ othersEffort) :
    linearBestResponseCandidate theta othersEffort ∈ FeasibleEffort := by
  exact ⟨linearBestResponseCandidate_nonnegative theta othersEffort,
    linearBestResponseCandidate_atMostOne theta othersEffort thetaAtMostOne
      othersNonnegative⟩

theorem linearBestResponseCandidate_continuous (theta : ℝ) :
    Continuous (linearBestResponseCandidate theta) := by
  unfold linearBestResponseCandidate
  fun_prop

theorem linearBestResponseCandidate_antitone (theta : ℝ) (thetaAtMostOne : theta ≤ 1) :
    Antitone (linearBestResponseCandidate theta) := by
  intro first second firstLeSecond
  unfold linearBestResponseCandidate
  apply max_le_max_left
  have coefficientNonnegative : 0 ≤ 1 - theta := sub_nonneg.mpr thetaAtMostOne
  have productOrder : (1 - theta) * first ≤ (1 - theta) * second :=
    mul_le_mul_of_nonneg_left firstLeSecond coefficientNonnegative
  linarith

theorem linearBestResponseCandidate_dist_le (theta first second : ℝ)
    (thetaAtMostOne : theta ≤ 1) :
    dist (linearBestResponseCandidate theta first)
        (linearBestResponseCandidate theta second) ≤
      (1 - theta) * dist first second := by
  unfold linearBestResponseCandidate
  rw [Real.dist_eq, Real.dist_eq]
  have maxBound := abs_max_sub_max_le_max (0 : ℝ)
    (theta - (1 - theta) * first) 0 (theta - (1 - theta) * second)
  calc
    _ ≤ max 0 |(theta - (1 - theta) * first) -
        (theta - (1 - theta) * second)| := by simpa only [sub_self, abs_zero] using maxBound
    _ = |(theta - (1 - theta) * first) -
        (theta - (1 - theta) * second)| := max_eq_right (abs_nonneg _)
    _ = (1 - theta) * |first - second| := by
      rw [show (theta - (1 - theta) * first) -
          (theta - (1 - theta) * second) = -(1 - theta) * (first - second) by ring,
        abs_mul, abs_neg, abs_of_nonneg (sub_nonneg.mpr thetaAtMostOne)]

theorem linearBestResponseCandidate_lipschitz (theta : ℝ)
    (thetaAtMostOne : theta ≤ 1) :
    LipschitzWith ⟨1 - theta, sub_nonneg.mpr thetaAtMostOne⟩
      (linearBestResponseCandidate theta) := by
  apply lipschitzWith_iff_dist_le_mul.mpr
  intro first second
  exact linearBestResponseCandidate_dist_le theta first second thetaAtMostOne

theorem linearBestResponseCandidate_eq_zero_iff (theta othersEffort : ℝ) :
    linearBestResponseCandidate theta othersEffort = 0 ↔
      theta ≤ (1 - theta) * othersEffort := by
  unfold linearBestResponseCandidate
  rw [max_eq_left_iff]
  constructor <;> intro assumption <;> linarith

/-- Away from the zero-effort floor, increasing coworkers' effort strictly
reduces the linear-production response candidate for an interior preference. -/
theorem linearBestResponseCandidate_strictAnti_of_positive (theta first second : ℝ)
    (thetaAtMostOne : theta < 1) (firstLtSecond : first < second)
    (secondPositive : 0 < linearBestResponseCandidate theta second) :
    linearBestResponseCandidate theta second < linearBestResponseCandidate theta first := by
  have coefficientPositive : 0 < 1 - theta := sub_pos.mpr thetaAtMostOne
  have expressionOrder :
      theta - (1 - theta) * second < theta - (1 - theta) * first := by
    nlinarith
  have secondExpressionPositive : 0 < theta - (1 - theta) * second := by
    simpa [linearBestResponseCandidate, max_eq_right (le_of_lt secondPositive)] using
      secondPositive
  rw [linearBestResponseCandidate, max_eq_right (le_of_lt secondExpressionPositive)]
  rw [linearBestResponseCandidate,
    max_eq_right (le_trans (le_of_lt secondExpressionPositive) (le_of_lt expressionOrder))]
  exact expressionOrder

def IsFeasibleFixedGroupProfile {groupSize : Nat}
    (profile : FixedGroupProfile groupSize) : Prop :=
  ∀ agent, profile agent ∈ FeasibleEffort

/-- A best-response map whose domain obligation is restricted to the feasible
effort cube. This is the economically relevant domain for fixed-group play. -/
def IsFeasibleFixedGroupBestResponseMap (params : Params) {groupSize : Nat}
    (theta : Fin groupSize → ℝ)
    (response : FixedGroupProfile groupSize → FixedGroupProfile groupSize) : Prop :=
  ∀ profile, IsFeasibleFixedGroupProfile profile → ∀ agent,
    IsBestResponse params (theta agent) (fixedGroupOtherEffort profile agent)
      groupSize (response profile agent)

def linearFixedGroupResponse {groupSize : Nat} (theta : Fin groupSize → ℝ)
    (profile : FixedGroupProfile groupSize) : FixedGroupProfile groupSize :=
  fun agent => linearBestResponseCandidate (theta agent)
    (fixedGroupOtherEffort profile agent)

theorem fixedGroupOtherEffort_nonnegative {groupSize : Nat}
    (profile : FixedGroupProfile groupSize) (profileFeasible : IsFeasibleFixedGroupProfile profile)
    (agent : Fin groupSize) : 0 ≤ fixedGroupOtherEffort profile agent := by
  unfold fixedGroupOtherEffort
  apply Finset.sum_nonneg
  intro other otherMem
  exact (profileFeasible other).1

theorem fixedGroupOtherEffort_dist_le {groupSize : Nat}
    (first second : FixedGroupProfile groupSize) (agent : Fin groupSize) :
    dist (fixedGroupOtherEffort first agent) (fixedGroupOtherEffort second agent) ≤
      (groupSize - 1 : Nat) * dist first second := by
  unfold fixedGroupOtherEffort
  rw [Real.dist_eq, ← Finset.sum_sub_distrib]
  calc
    |∑ other ∈ Finset.univ.filter (· ≠ agent), (first other - second other)| ≤
        ∑ other ∈ Finset.univ.filter (· ≠ agent), |first other - second other| :=
      Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ _other ∈ Finset.univ.filter (· ≠ agent), dist first second := by
      apply Finset.sum_le_sum
      intro other otherMem
      rw [← Real.dist_eq]
      exact (dist_pi_le_iff dist_nonneg).mp le_rfl other
    _ = (groupSize - 1 : Nat) * dist first second := by
      have filterEq : Finset.univ.filter (· ≠ agent) = Finset.univ.erase agent := by
        ext other
        simp [eq_comm]
      rw [filterEq, Finset.sum_const, Finset.card_erase_of_mem (Finset.mem_univ agent)]
      simp

theorem linearFixedGroupResponse_feasible {groupSize : Nat}
    (theta : Fin groupSize → ℝ) (thetaAtMostOne : ∀ agent, theta agent ≤ 1)
    (profile : FixedGroupProfile groupSize) (profileFeasible : IsFeasibleFixedGroupProfile profile) :
    IsFeasibleFixedGroupProfile (linearFixedGroupResponse theta profile) := by
  intro agent
  exact linearBestResponseCandidate_feasible (theta agent)
    (fixedGroupOtherEffort profile agent) (thetaAtMostOne agent)
    (fixedGroupOtherEffort_nonnegative profile profileFeasible agent)

theorem linearFixedGroupResponse_continuous {groupSize : Nat}
    (theta : Fin groupSize → ℝ) : Continuous (linearFixedGroupResponse theta) := by
  unfold linearFixedGroupResponse linearBestResponseCandidate fixedGroupOtherEffort
  fun_prop

def interactionCount (groupSize : Nat) : NNReal :=
  let count : Nat := groupSize - 1
  ⟨(count : ℝ), Nat.cast_nonneg count⟩

theorem linearFixedGroupResponse_lipschitz {groupSize : Nat}
    (theta : Fin groupSize → ℝ) (K : NNReal)
    (thetaAtMostOne : ∀ agent, theta agent ≤ 1)
    (coefficientBound : ∀ agent, 1 - theta agent ≤ (K : ℝ)) :
    LipschitzWith (K * interactionCount groupSize)
      (linearFixedGroupResponse theta) := by
  apply lipschitzWith_iff_dist_le_mul.mpr
  intro first second
  apply (dist_pi_le_iff (mul_nonneg (by positivity) dist_nonneg)).2
  intro agent
  have scalarBound := linearBestResponseCandidate_dist_le (theta agent)
    (fixedGroupOtherEffort first agent) (fixedGroupOtherEffort second agent)
    (thetaAtMostOne agent)
  have othersBound := fixedGroupOtherEffort_dist_le first second agent
  change dist
      (linearBestResponseCandidate (theta agent) (fixedGroupOtherEffort first agent))
      (linearBestResponseCandidate (theta agent) (fixedGroupOtherEffort second agent)) ≤
        (K : ℝ) * ((groupSize - 1 : Nat) : ℝ) * dist first second
  calc
    _ ≤ (1 - theta agent) *
        dist (fixedGroupOtherEffort first agent) (fixedGroupOtherEffort second agent) := scalarBound
    _ ≤ (K : ℝ) * ((groupSize - 1 : Nat) * dist first second) :=
      mul_le_mul (coefficientBound agent) othersBound dist_nonneg
        K.coe_nonneg
    _ = (K : ℝ) * ((groupSize - 1 : Nat) : ℝ) * dist first second := by ring

theorem linearFixedGroupResponse_contracting {groupSize : Nat}
    (theta : Fin groupSize → ℝ) (K : NNReal)
    (thetaAtMostOne : ∀ agent, theta agent ≤ 1)
    (coefficientBound : ∀ agent, 1 - theta agent ≤ (K : ℝ))
    (contractionBound : K * interactionCount groupSize < 1) :
    ContractingWith (K * interactionCount groupSize) (linearFixedGroupResponse theta) :=
  ⟨contractionBound,
    linearFixedGroupResponse_lipschitz theta K thetaAtMostOne coefficientBound⟩

theorem linearFixedGroupResponse_fixedPoint_feasible {groupSize : Nat}
    (theta : Fin groupSize → ℝ) (thetaAtMostOne : ∀ agent, theta agent ≤ 1)
    (profile : FixedGroupProfile groupSize)
    (fixedPoint : linearFixedGroupResponse theta profile = profile) :
    IsFeasibleFixedGroupProfile profile := by
  have profileNonnegative : ∀ agent, 0 ≤ profile agent := by
    intro agent
    have coordinateFixed := congrFun fixedPoint agent
    rw [← coordinateFixed]
    exact linearBestResponseCandidate_nonnegative _ _
  intro agent
  refine ⟨profileNonnegative agent, ?_⟩
  have othersNonnegative : 0 ≤ fixedGroupOtherEffort profile agent := by
    unfold fixedGroupOtherEffort
    exact Finset.sum_nonneg fun other _ => profileNonnegative other
  have responseAtMostOne := linearBestResponseCandidate_atMostOne (theta agent)
    (fixedGroupOtherEffort profile agent) (thetaAtMostOne agent) othersNonnegative
  have coordinateFixed := congrFun fixedPoint agent
  rw [← coordinateFixed]
  exact responseAtMostOne

theorem exists_linearFixedGroupNash_of_contraction
    (params : Params) {groupSize : Nat} (theta : Fin groupSize → ℝ) (K : NNReal)
    (linearProduction : params.b = 0) (aNonnegative : 0 ≤ params.a)
    (thetaNonnegative : ∀ agent, 0 ≤ theta agent)
    (thetaLessThanOne : ∀ agent, theta agent < 1)
    (coefficientBound : ∀ agent, 1 - theta agent ≤ (K : ℝ))
    (contractionBound : K * interactionCount groupSize < 1) :
    ∃ profile, IsFixedGroupNash params theta profile := by
  let contracting := linearFixedGroupResponse_contracting theta K
    (fun agent => (thetaLessThanOne agent).le) coefficientBound contractionBound
  let profile := ContractingWith.fixedPoint (linearFixedGroupResponse theta) contracting
  have fixedPoint : linearFixedGroupResponse theta profile = profile :=
    contracting.fixedPoint_isFixedPt
  have feasible := linearFixedGroupResponse_fixedPoint_feasible theta
    (fun agent => (thetaLessThanOne agent).le) profile fixedPoint
  refine ⟨profile, ?_⟩
  intro agent
  have best := linearBestResponseCandidate_isBestResponse params (theta agent)
    (fixedGroupOtherEffort profile agent) groupSize linearProduction aNonnegative
    (thetaNonnegative agent) (thetaLessThanOne agent)
    (fixedGroupOtherEffort_nonnegative profile feasible agent)
  have coordinateFixed := congrFun fixedPoint agent
  rw [← coordinateFixed]
  exact best

theorem tendsto_linearFixedGroupNash_of_contraction
    (params : Params) {groupSize : Nat} (theta : Fin groupSize → ℝ) (K : NNReal)
    (linearProduction : params.b = 0) (aNonnegative : 0 ≤ params.a)
    (thetaNonnegative : ∀ agent, 0 ≤ theta agent)
    (thetaLessThanOne : ∀ agent, theta agent < 1)
    (coefficientBound : ∀ agent, 1 - theta agent ≤ (K : ℝ))
    (contractionBound : K * interactionCount groupSize < 1)
    (initial : FixedGroupProfile groupSize) :
    ∃ equilibrium, IsFixedGroupNash params theta equilibrium ∧
      Filter.Tendsto (fun iteration => (linearFixedGroupResponse theta)^[iteration] initial)
        Filter.atTop (nhds equilibrium) := by
  let contracting := linearFixedGroupResponse_contracting theta K
    (fun agent => (thetaLessThanOne agent).le) coefficientBound contractionBound
  let equilibrium := ContractingWith.fixedPoint (linearFixedGroupResponse theta) contracting
  have fixedPoint : linearFixedGroupResponse theta equilibrium = equilibrium :=
    contracting.fixedPoint_isFixedPt
  have feasible := linearFixedGroupResponse_fixedPoint_feasible theta
    (fun agent => (thetaLessThanOne agent).le) equilibrium fixedPoint
  have equilibriumNash : IsFixedGroupNash params theta equilibrium := by
    intro agent
    have best := linearBestResponseCandidate_isBestResponse params (theta agent)
      (fixedGroupOtherEffort equilibrium agent) groupSize linearProduction aNonnegative
      (thetaNonnegative agent) (thetaLessThanOne agent)
      (fixedGroupOtherEffort_nonnegative equilibrium feasible agent)
    have coordinateFixed := congrFun fixedPoint agent
    rw [← coordinateFixed]
    exact best
  refine ⟨equilibrium, equilibriumNash, ?_⟩
  exact contracting.tendsto_iterate_fixedPoint initial

theorem existsUnique_linearFixedGroupNash_of_contraction
    (params : Params) {groupSize : Nat} (theta : Fin groupSize → ℝ) (K : NNReal)
    (linearProduction : params.b = 0) (aPositive : 0 < params.a)
    (groupSizePositive : 0 < groupSize)
    (thetaNonnegative : ∀ agent, 0 ≤ theta agent)
    (thetaLessThanOne : ∀ agent, theta agent < 1)
    (coefficientBound : ∀ agent, 1 - theta agent ≤ (K : ℝ))
    (contractionBound : K * interactionCount groupSize < 1) :
    ∃! profile, IsFixedGroupNash params theta profile := by
  let contracting := linearFixedGroupResponse_contracting theta K
    (fun agent => (thetaLessThanOne agent).le) coefficientBound contractionBound
  let profile := ContractingWith.fixedPoint (linearFixedGroupResponse theta) contracting
  have profileFixed : linearFixedGroupResponse theta profile = profile :=
    contracting.fixedPoint_isFixedPt
  have profileFeasible := linearFixedGroupResponse_fixedPoint_feasible theta
    (fun agent => (thetaLessThanOne agent).le) profile profileFixed
  have profileNash : IsFixedGroupNash params theta profile := by
    intro agent
    have best := linearBestResponseCandidate_isBestResponse params (theta agent)
      (fixedGroupOtherEffort profile agent) groupSize linearProduction aPositive.le
      (thetaNonnegative agent) (thetaLessThanOne agent)
      (fixedGroupOtherEffort_nonnegative profile profileFeasible agent)
    have coordinateFixed := congrFun profileFixed agent
    rw [← coordinateFixed]
    exact best
  refine ⟨profile, profileNash, ?_⟩
  intro other otherNash
  have otherFixed : linearFixedGroupResponse theta other = other := by
    funext agent
    apply Eq.symm
    exact linearBestResponseCandidate_unique params (theta agent)
      (fixedGroupOtherEffort other agent) (other agent) groupSize linearProduction
      aPositive groupSizePositive (thetaNonnegative agent) (thetaLessThanOne agent)
      (fixedGroupOtherEffort_nonnegative other (fun member => (otherNash member).1) agent)
      (otherNash agent)
  exact contracting.fixedPoint_unique' otherFixed profileFixed

theorem linearFixedGroupResponse_isBestResponseMap
    (params : Params) {groupSize : Nat} (theta : Fin groupSize → ℝ)
    (linearProduction : params.b = 0) (aNonnegative : 0 ≤ params.a)
    (thetaNonnegative : ∀ agent, 0 ≤ theta agent)
    (thetaLessThanOne : ∀ agent, theta agent < 1) :
    IsFeasibleFixedGroupBestResponseMap params theta (linearFixedGroupResponse theta) := by
  intro profile profileFeasible agent
  exact linearBestResponseCandidate_isBestResponse params (theta agent)
    (fixedGroupOtherEffort profile agent) groupSize linearProduction aNonnegative
    (thetaNonnegative agent) (thetaLessThanOne agent)
    (fixedGroupOtherEffort_nonnegative profile profileFeasible agent)

theorem feasible_fixedPoint_of_linearResponse_is_nash
    (params : Params) {groupSize : Nat} (theta : Fin groupSize → ℝ)
    (linearProduction : params.b = 0) (aNonnegative : 0 ≤ params.a)
    (thetaNonnegative : ∀ agent, 0 ≤ theta agent)
    (thetaLessThanOne : ∀ agent, theta agent < 1)
    (profile : FixedGroupProfile groupSize) (profileFeasible : IsFeasibleFixedGroupProfile profile)
    (fixedPoint : linearFixedGroupResponse theta profile = profile) :
    IsFixedGroupNash params theta profile := by
  intro agent
  have best := linearFixedGroupResponse_isBestResponseMap params theta linearProduction
    aNonnegative thetaNonnegative thetaLessThanOne profile profileFeasible agent
  rw [fixedPoint] at best
  exact best

noncomputable def symmetricLinearEquilibriumEffort (theta : ℝ) (groupSize : Nat) : ℝ :=
  theta / (1 + (1 - theta) * (groupSize - 1 : Nat))

theorem fixedGroupOtherEffort_const {groupSize : Nat} (effort : ℝ)
    (agent : Fin groupSize) :
    fixedGroupOtherEffort (fun _ : Fin groupSize => effort) agent =
      (groupSize - 1 : Nat) * effort := by
  unfold fixedGroupOtherEffort
  have filterEq : Finset.univ.filter (· ≠ agent) = Finset.univ.erase agent := by
    ext other
    simp [eq_comm]
  rw [filterEq, Finset.sum_const, Finset.card_erase_of_mem (Finset.mem_univ agent)]
  simp

theorem symmetricLinearEquilibriumEffort_positive (theta : ℝ) (groupSize : Nat)
    (thetaPositive : 0 < theta) (thetaAtMostOne : theta < 1) :
    0 < symmetricLinearEquilibriumEffort theta groupSize := by
  unfold symmetricLinearEquilibriumEffort
  apply div_pos thetaPositive
  have coefficientNonnegative : 0 ≤ 1 - theta := (sub_pos.mpr thetaAtMostOne).le
  have countNonnegative : (0 : ℝ) ≤ (groupSize - 1 : Nat) := Nat.cast_nonneg _
  linarith [mul_nonneg coefficientNonnegative countNonnegative]

theorem symmetricLinearEquilibriumEffort_atMostOne (theta : ℝ) (groupSize : Nat)
    (thetaPositive : 0 < theta) (thetaAtMostOne : theta < 1) :
    symmetricLinearEquilibriumEffort theta groupSize ≤ 1 := by
  unfold symmetricLinearEquilibriumEffort
  have coefficientNonnegative : 0 ≤ 1 - theta := (sub_pos.mpr thetaAtMostOne).le
  have countNonnegative : (0 : ℝ) ≤ (groupSize - 1 : Nat) := Nat.cast_nonneg _
  have productNonnegative : 0 ≤ (1 - theta) * (groupSize - 1 : Nat) :=
    mul_nonneg coefficientNonnegative countNonnegative
  have denominatorPositive : 0 < 1 + (1 - theta) * (groupSize - 1 : Nat) := by
    linarith
  apply (div_le_one denominatorPositive).2
  linarith

theorem symmetricLinearProfile_fixedPoint (theta : ℝ) (groupSize : Nat)
    (thetaPositive : 0 < theta) (thetaAtMostOne : theta < 1) :
    linearFixedGroupResponse (fun _ : Fin groupSize => theta)
        (fun _ : Fin groupSize => symmetricLinearEquilibriumEffort theta groupSize) =
      (fun _ : Fin groupSize => symmetricLinearEquilibriumEffort theta groupSize) := by
  funext agent
  rw [linearFixedGroupResponse, fixedGroupOtherEffort_const]
  unfold linearBestResponseCandidate symmetricLinearEquilibriumEffort
  have coefficientNonnegative : 0 ≤ 1 - theta := (sub_pos.mpr thetaAtMostOne).le
  have countNonnegative : (0 : ℝ) ≤ (groupSize - 1 : Nat) := Nat.cast_nonneg _
  have productNonnegative : 0 ≤ (1 - theta) * (groupSize - 1 : Nat) :=
    mul_nonneg coefficientNonnegative countNonnegative
  have denominatorPositive : 0 < 1 + (1 - theta) * (groupSize - 1 : Nat) := by
    linarith
  have expressionEq :
      theta - (1 - theta) *
          ((groupSize - 1 : Nat) *
            (theta / (1 + (1 - theta) * (groupSize - 1 : Nat)))) =
        theta / (1 + (1 - theta) * (groupSize - 1 : Nat)) := by
    field_simp
    ring
  rw [max_eq_right]
  · exact expressionEq
  · rw [expressionEq]
    exact (div_pos thetaPositive denominatorPositive).le

theorem symmetricLinearProfile_is_nash
    (params : Params) (theta : ℝ) (groupSize : Nat)
    (linearProduction : params.b = 0) (aNonnegative : 0 ≤ params.a)
    (thetaPositive : 0 < theta) (thetaAtMostOne : theta < 1) :
    IsFixedGroupNash params (fun _ : Fin groupSize => theta)
      (fun _ : Fin groupSize => symmetricLinearEquilibriumEffort theta groupSize) := by
  apply feasible_fixedPoint_of_linearResponse_is_nash params
    (fun _ : Fin groupSize => theta) linearProduction aNonnegative
    (fun _ => thetaPositive.le) (fun _ => thetaAtMostOne)
  · intro agent
    exact ⟨(symmetricLinearEquilibriumEffort_positive theta groupSize thetaPositive
      thetaAtMostOne).le,
      symmetricLinearEquilibriumEffort_atMostOne theta groupSize thetaPositive thetaAtMostOne⟩
  · exact symmetricLinearProfile_fixedPoint theta groupSize thetaPositive thetaAtMostOne

end AgenticAxtell.Baseline
